### ISSUE TITLE
Failed to virtualize on Windows 10 Build 10586 x64

### ISSUE THREAD

**Issue by f32y** [Nukem9/VirtualDbg#1]
Hello,

I compiled your code in VS2015 and loaded the driver on Win10 x64, however it failed.

The log shows AllocateVmxProcessorData() failed to allocate memory.

```
    if (*Size <= 0)
    {
        // In rare cases this isn't set (*COUGH* *VMWARE*)
        if (msr.szVmxOnRegion > 0)
            *Size = msr.szVmxOnRegion;
        else
            *Size = 0x1000;

        *Size = ROUND_TO_PAGES(*Size);
    }
```

How can I fix this bug?

**Comment by f32y** [comment]
After I replaced MmAllocateContiguousMemorySpecifyCache() with MmAllocateNonCachedMemory() in ControlAreaInitializeProcessor(), the code runs successfully:) 

Why?

**Comment by Nukem9** [comment]
Note: most code was tested and is still **incomplete**, but `MmAllocateContiguousMemorySpecifyCache` might fail because of you OS/CPU type/free memory. I don't have a specific reason.

`MmAllocateNonCachedMemory` also doesn't allocate pages that are contiguous (they are only cache aligned).

**Comment by f32y** [comment]
Thanks. I should know more about these two functions:)

**Comment by f32y** [comment]
The StartVirtualization() is called in IpiStartVirtualization() which is called by 
`KeIpiGenericCall(IpiStartVirtualization, 0);`in `Vm.cpp`. When KeIpiGenericCall is called, the IRQL will be set to IPI_LEVEL, which is much higher than DISPATCH_LEVEL.

https://msdn.microsoft.com/en-us/library/windows/hardware/ff554464(v=vs.85).aspx

Here ms says MmAllocateContiguousMemorySpecifyCache() should be called at IRQL <=   DISPATCH_LEVEL, or the memory allocation may fail.

After I changed `KeIpiGenericCall(IpiStartVirtualization, 0);` 
to

```
    KAFFINITY OldAffinity;
    KIRQL OldIrql;
    for (ULONG i = 0; i < (ULONG)KeNumberProcessors; i++)
    {
        OldAffinity = KeSetSystemAffinityThreadEx((KAFFINITY)(1 << i));
        OldIrql = KeRaiseIrqlToDpcLevel();
        _StartVirtualization();
        KeLowerIrql(OldIrql);
        KeRevertToUserAffinityThreadEx(OldAffinity);
    }
```

It runs well:)

**Comment by Nukem9** [comment]
Supposedly fixed in https://github.com/Nukem9/VirtualDbg/pull/2.
